sudo: false
language: python
services:
- postgresql
- elasticsearch
- redis-server
python:
- 2.7
- 3.4
- 3.5
- 3.6
install:
- pip install -U pip setuptools
- pip install tox-travis
- pip install -r requirements.txt -r test_requirements.txt
before_script:
- psql -c 'create database test_postgres;' -U postgres
script:
- tox
