sudo: required
language: python
services:
  - postgresql
  - elasticsearch
  - redis-server
  - rabbitmq
install:
  - pip install -U pip setuptools
  - pip install tox-travis
  - pip install -r requirements.txt -r test_requirements.txt
before_script:
  - psql -c 'create database test_postgres;' -U postgres
matrix:
  include:
    - python: 3.7
      env: TOX_ENV=django20
    - python: 3.7
      env: TOX_ENV=django30
    - python: 3.8
      env: TOX_ENV=django20
    - python: 3.8
      env: TOX_ENV=django30
script: tox -e $TOX_ENV
