sudo: false
language: python
services:
  - postgresql
  - elasticsearch
  - redis-server
install:
  - pip install -U pip setuptools
  - pip install tox-travis
  - pip install -r requirements.txt -r test_requirements.txt
before_script:
  - psql -c 'create database test_postgres;' -U postgres
matrix:
  include:
    - python: 2.7
      env: TOX_ENV=django110
    - python: 2.7
      env: TOX_ENV=django111
    - python: 3.6
      env: TOX_ENV=django110
    - python: 3.6
      env: TOX_ENV=django111
    - python: 3.6
      env: TOX_ENV=django20
script: tox -e $TOX_ENV
